services:
<<<<<<< HEAD

=======
  mysql:
    container_name: mysql-container
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: "%" # Allow root access from any host
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - apis-network
    restart: always
    # Healthcheck for mysql container
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s
>>>>>>> 8ea5293bc147863998b5331d4fd7eb2f4226a11a
  identity.api:
    image: identity-api
    build:
      context: .
      dockerfile: Services/Identity.API/Dockerfile
    networks:
      - apis-network
<<<<<<< HEAD
=======
    depends_on:
      mysql:
        condition: service_healthy
>>>>>>> 8ea5293bc147863998b5331d4fd7eb2f4226a11a
  room.api:
    image: room-api
    build:
      context: .
      dockerfile: Services/Room.API/Dockerfile
    networks:
      - apis-network
    depends_on:
<<<<<<< HEAD
      rabbitmq:
=======
      mysql:
>>>>>>> 8ea5293bc147863998b5331d4fd7eb2f4226a11a
        condition: service_healthy
  tour.api:
    image: tour-api
    build:
      context: .
      dockerfile: Services/Tour.API/Dockerfile
    networks:
      - apis-network
    depends_on:
<<<<<<< HEAD
      rabbitmq:
=======
      mysql:
>>>>>>> 8ea5293bc147863998b5331d4fd7eb2f4226a11a
        condition: service_healthy
  booking.api:
    image: booking-api
    build: 
      context: .
      dockerfile: Services/Booking.API/Dockerfile
    networks:
      - apis-network
    depends_on:
<<<<<<< HEAD
      rabbitmq:
        condition: service_healthy
  realtime.api:
    image: realtime-api
    build: 
      context: .
      dockerfile: Services/Realtime.API/Dockerfile
    networks:
      - apis-network
    depends_on:
      rabbitmq:
=======
      mysql:
>>>>>>> 8ea5293bc147863998b5331d4fd7eb2f4226a11a
        condition: service_healthy
  rabbitmq:
    container_name: rabbitmq-container
    image: rabbitmq:3-management-alpine
    networks:
      - apis-network
    ports:
      - 5672:5672
      - 15672:15672
<<<<<<< HEAD
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

=======
>>>>>>> 8ea5293bc147863998b5331d4fd7eb2f4226a11a
  upload.api:
    image: upload-api
    build:
        context: .
        dockerfile: Services/Upload.API/Dockerfile
    networks:
      - apis-network  
<<<<<<< HEAD

=======
>>>>>>> 8ea5293bc147863998b5331d4fd7eb2f4226a11a
  api_gateway:
    image: api-gateway
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile
    depends_on:
      - identity.api
      - room.api
      - tour.api
      - booking.api
<<<<<<< HEAD
      - saga.api
      - realtime.api
    networks:
      - apis-network

  saga.api:
    image: saga-api
    build:
      context: .
      dockerfile: Saga.Orchestrator/Saga.Orchestrator/Dockerfile
=======
>>>>>>> 8ea5293bc147863998b5331d4fd7eb2f4226a11a
    networks:
      - apis-network
networks:
  apis-network:
<<<<<<< HEAD
=======
    
volumes:
  mysql_data:
    name: mysql_data
>>>>>>> 8ea5293bc147863998b5331d4fd7eb2f4226a11a
