services:
  identity.api:
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DatabaseSettings:ConnectionString=server=${DB_SERVER};port=${DB_PORT};database=new_booking_identity;user=${DB_USER};password=${DB_PASSWORD}
    ports:
      - "5001:80"
    restart: always
  room.api:
    container_name: room.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DatabaseSettings:ConnectionString=server=${DB_SERVER};port=${DB_PORT};database=new_booking_room;user=${DB_USER};password=${DB_PASSWORD}
    ports:
      - "5003:80"
    restart: always
  tour.api:
    container_name: tour.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DatabaseSettings:ConnectionString=server=${DB_SERVER};port=${DB_PORT};database=new_booking_tour;user=${DB_USER};password=${DB_PASSWORD}
    ports:
      - "5004:80"
    restart: always
  upload.api:
    container_name: upload.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5005:80"
    volumes:
      - ~/.aws:/root/.aws:ro
    restart: always 
  api_gateway:
    container_name: api_gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DatabaseSettings:ConnectionString=server=${DB_SERVER};port=${DB_PORT};database=new_booking_tour;user=${DB_USER};password=${DB_PASSWORD}
    ports:
      - "5000:80"
