services:
  identity.api:
    container_name: identity-api
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80;http://+:81
    ports:
      - "5001:80"
      - "5101:81"
  room.api:
    container_name: room-api
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80;http://+:81
    ports:
      - "5003:80"
      - "5103:81"
  tour.api:
    container_name: tour-api
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80;http://+:81
    ports:
      - "5004:80"
      - "5104:81"
 
  healthstatus:
    container_name: healthstatus
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80;http://+:81 
      - HealthChecksUI__HealthChecks__0__Name=Booking Health Check
      - HealthChecksUI__HealthChecks__0__Uri=http://booking.api:81/hc
      - HealthChecksUI__HealthChecks__1__Name=Identity Health Check
      - HealthChecksUI__HealthChecks__1__Uri=http://identity-api:81/hc
      - HealthChecksUI__HealthChecks__2__Name=Realtime Health Check
      - HealthChecksUI__HealthChecks__2__Uri=http://realtime.api:81/hc
      - HealthChecksUI__HealthChecks__3__Name=Room Health Check
      - HealthChecksUI__HealthChecks__3__Uri=http://room-api:81/hc
      - HealthChecksUI__HealthChecks__4__Name=Tour Health Check
      - HealthChecksUI__HealthChecks__4__Uri=http://tour-api/hc
      - HealthChecksUI__HealthChecks__5__Name=Upload Health Check
      - HealthChecksUI__HealthChecks__5__Uri=http://upload.api:81/hc
      - HealthChecksUI__HealthChecks__6__Name=Background Job Health Check
      - HealthChecksUI__HealthChecks__6__Uri=http://hangfire.api:81/hc
    ports:
      - "5010:80"
      - "5110:81"
  booking.api:
    container_name: booking.api
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80;http://+:81
    ports:
      - "5002:80"
      - "5102:81"
    restart: always
  upload.api:
    container_name: upload.api
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5005:80"
    volumes:
      - ~/.aws:/root/.aws:ro
    restart: always
  api_gateway:
    container_name: api_gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "6000:443"
      - "5000:80"
  saga.api:
    container_name: saga.api
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5007:80"
  background.api:
    container_name: hangfire.api
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80 
    ports:
      - "5009:80"
  realtime.api:
    container_name:  realtime.api
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80 
    ports:
      - "5008:80"

  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elasticsearch
      - ELASTICSEARCH_PASSWORF=admin
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
